### ISSUE TITLE
Build simple python projects

### ISSUE THREAD

**Issue by Crazy2code15** [Crazy2code15/Python-Projects#1]
Step By Step:

star and fork this repo
build your simple project you like
add your name in CONTRIBUTING.md
pull request
done
Thank you for participate with this repo. let's connect with me by following me in github.

**Comment by YUG-RAVAL** [comment]
Can I add the square Root Program in Python?

**Comment by SakshiJoshi26** [comment]
Can I add a program to rotate a matrix in python?

**Comment by Crazy2code15** [comment]
> Can I add a program to rotate a matrix in python?

Yes, You can add

**Comment by Crazy2code15** [comment]
> Can I add the square Root Program in Python?

yes you can add

**Comment by Crazy2code15** [comment]
> I want to add a script to restart/shutdown your system ^^

Yes you can add
